DOMAIN = "skylight_local"
PLATFORMS = ["sensor", "select", "number", "button", "switch"]
CONF_LAMP_IP = "lamp_ip"
DATA_CONTROLLER = "controller"
DEFAULT_POWER = 30
MODE_OFF = "off"
MODE_AUTO = "auto"
MODE_MANUAL = "manual"
MODE_DEMO = "demo"
